/** Spotify Extended Streaming History — generated by SpethialLab analyze.py */
export const musicStats = {
  "meta": {
    "dateRange": {
      "first": "2016-11-14",
      "last": "2026-05-21"
    },
    "generatedAt": "2026-05-24",
    "totalPlayEvents": 129880
  },
  "overview": {
    "totalMusicHours": 6806.6,
    "totalPodcastHours": 61.7,
    "uniqueTracks": 36589,
    "uniqueArtists": 9516,
    "avgHoursPerMonth": 59.2,
    "busiestMonth": {
      "label": "2018-02",
      "hours": 118
    }
  },
  "topArtists": [
    {
      "name": "Hybrid Minds",
      "hours": 217.9,
      "plays": 3346,
      "skipRate": 8.4,
      "genres": [
        "liquid funk",
        "drum and bass"
      ],
      "firstListen": "2018-05-07"
    },
    {
      "name": "SIX60",
      "hours": 105.3,
      "plays": 1959,
      "skipRate": 9.5,
      "genres": [
        "nz reggae"
      ],
      "firstListen": "2016-12-01"
    },
    {
      "name": "Deftones",
      "hours": 95.0,
      "plays": 1429,
      "skipRate": 12.2,
      "genres": [
        "nu metal",
        "alternative metal",
        "rap metal"
      ],
      "firstListen": "2017-02-23"
    },
    {
      "name": "Miracle Tones",
      "hours": 85.2,
      "plays": 1987,
      "skipRate": 3.0,
      "genres": [],
      "firstListen": "2024-10-13"
    },
    {
      "name": "Wolfgang Amadeus Mozart",
      "hours": 82.0,
      "plays": 1015,
      "skipRate": 9.2,
      "genres": [
        "classical",
        "classical piano",
        "opera"
      ],
      "firstListen": "2017-04-21"
    },
    {
      "name": "Foo Fighters",
      "hours": 74.3,
      "plays": 1269,
      "skipRate": 14.1,
      "genres": [
        "post-grunge",
        "rock",
        "alternative rock"
      ],
      "firstListen": "2017-05-10"
    },
    {
      "name": "R3HAB",
      "hours": 69.7,
      "plays": 1796,
      "skipRate": 11.7,
      "genres": [
        "slap house",
        "edm"
      ],
      "firstListen": "2017-03-04"
    },
    {
      "name": "Chase & Status",
      "hours": 64.0,
      "plays": 1204,
      "skipRate": 15.1,
      "genres": [
        "drum and bass",
        "jungle"
      ],
      "firstListen": "2016-12-21"
    },
    {
      "name": "PLÜM",
      "hours": 55.2,
      "plays": 1232,
      "skipRate": 6.6,
      "genres": [],
      "firstListen": "2020-09-21"
    },
    {
      "name": "Logic",
      "hours": 48.1,
      "plays": 824,
      "skipRate": 11.0,
      "genres": [],
      "firstListen": "2017-10-16"
    },
    {
      "name": "Muse",
      "hours": 48.0,
      "plays": 792,
      "skipRate": 11.7,
      "genres": [
        "alternative rock",
        "rock"
      ],
      "firstListen": "2016-11-14"
    },
    {
      "name": "Ed Sheeran",
      "hours": 46.7,
      "plays": 813,
      "skipRate": 11.6,
      "genres": [
        "soft pop"
      ],
      "firstListen": "2017-01-06"
    },
    {
      "name": "Netsky",
      "hours": 46.2,
      "plays": 831,
      "skipRate": 12.5,
      "genres": [
        "drum and bass",
        "liquid funk",
        "chillstep"
      ],
      "firstListen": "2017-07-29"
    },
    {
      "name": "ILLENIUM",
      "hours": 44.3,
      "plays": 766,
      "skipRate": 8.4,
      "genres": [
        "melodic bass",
        "future bass",
        "edm"
      ],
      "firstListen": "2017-07-14"
    },
    {
      "name": "Desolent",
      "hours": 42.7,
      "plays": 842,
      "skipRate": 5.6,
      "genres": [
        "witch house",
        "trap soul",
        "dark r&b"
      ],
      "firstListen": "2022-03-10"
    },
    {
      "name": "Khalid",
      "hours": 40.9,
      "plays": 819,
      "skipRate": 11.0,
      "genres": [],
      "firstListen": "2017-08-23"
    },
    {
      "name": "Summer Walker",
      "hours": 40.3,
      "plays": 1031,
      "skipRate": 10.4,
      "genres": [
        "r&b"
      ],
      "firstListen": "2018-08-14"
    },
    {
      "name": "Ludwig van Beethoven",
      "hours": 39.7,
      "plays": 440,
      "skipRate": 7.5,
      "genres": [
        "classical",
        "classical piano",
        "chamber music"
      ],
      "firstListen": "2016-12-01"
    },
    {
      "name": "Drake",
      "hours": 39.3,
      "plays": 707,
      "skipRate": 12.3,
      "genres": [
        "rap"
      ],
      "firstListen": "2017-02-22"
    },
    {
      "name": "Rudimental",
      "hours": 37.3,
      "plays": 729,
      "skipRate": 16.9,
      "genres": [],
      "firstListen": "2017-01-09"
    }
  ],
  "topTracks": [
    {
      "name": "417 Hz Clear Negative Energy",
      "artist": "Miracle Tones",
      "plays": 388,
      "hours": 18.5,
      "skipRate": 2.6
    },
    {
      "name": "396 Hz Cleanse Fear & Negative Blocks",
      "artist": "Miracle Tones",
      "plays": 383,
      "hours": 18.7,
      "skipRate": 1.3
    },
    {
      "name": "741 Hz Spiritual Detox",
      "artist": "Miracle Tones",
      "plays": 377,
      "hours": 14.6,
      "skipRate": 1.6
    },
    {
      "name": "741 Hz Cleanse Aura",
      "artist": "Miracle Tones",
      "plays": 374,
      "hours": 14.9,
      "skipRate": 9.1
    },
    {
      "name": "Exogenesis: Symphony Pt. 3 (Redemption)",
      "artist": "Muse",
      "plays": 138,
      "hours": 10.0,
      "skipRate": 3.6
    },
    {
      "name": "Green Bottles",
      "artist": "SIX60",
      "plays": 119,
      "hours": 7.2,
      "skipRate": 6.7
    },
    {
      "name": "Don’t Matter To Me (with Michael Jackson)",
      "artist": "Drake",
      "plays": 116,
      "hours": 7.5,
      "skipRate": 4.3
    },
    {
      "name": "Change (In the House of Flies)",
      "artist": "Deftones",
      "plays": 108,
      "hours": 9.0,
      "skipRate": 5.6
    },
    {
      "name": "Touch",
      "artist": "Hybrid Minds",
      "plays": 99,
      "hours": 7.7,
      "skipRate": 12.1
    },
    {
      "name": "My Own Summer (Shove It)",
      "artist": "Deftones",
      "plays": 97,
      "hours": 5.7,
      "skipRate": 7.2
    },
    {
      "name": "How I Fall Apart",
      "artist": "Currents",
      "plays": 96,
      "hours": 6.5,
      "skipRate": 11.5
    },
    {
      "name": "Scared to Be Lonely - Acoustic Version",
      "artist": "Martin Garrix",
      "plays": 91,
      "hours": 5.6,
      "skipRate": 9.9
    },
    {
      "name": "How Many Drinks?",
      "artist": "Miguel",
      "plays": 90,
      "hours": 5.3,
      "skipRate": 14.4
    },
    {
      "name": "Exogenesis: Symphony Pt. 1 (Overture)",
      "artist": "Muse",
      "plays": 89,
      "hours": 5.7,
      "skipRate": 6.7
    },
    {
      "name": "Slowfi",
      "artist": "Its Sonny",
      "plays": 87,
      "hours": 3.3,
      "skipRate": 1.1
    },
    {
      "name": "Change (In the House of Flies) - Acoustic; 2005 Remaster",
      "artist": "Deftones",
      "plays": 86,
      "hours": 6.5,
      "skipRate": 10.5
    },
    {
      "name": "Forever (feat. Elohim) - Laxcity Remix",
      "artist": "Ekali",
      "plays": 86,
      "hours": 4.6,
      "skipRate": 9.3
    },
    {
      "name": "So Sick - Acoustic",
      "artist": "Ne-Yo",
      "plays": 85,
      "hours": 3.1,
      "skipRate": 27.1
    },
    {
      "name": "Better Days",
      "artist": "Currents",
      "plays": 85,
      "hours": 4.5,
      "skipRate": 31.8
    },
    {
      "name": "Pickle Rick",
      "artist": "愛THE BLXCK SINATRA死",
      "plays": 84,
      "hours": 2.6,
      "skipRate": 13.1
    }
  ],
  "topGenres": [
    {
      "genre": "drum and bass",
      "hours": 681.3,
      "pct": 8.9,
      "trend": "rising",
      "artistCount": 71
    },
    {
      "genre": "edm",
      "hours": 642.3,
      "pct": 8.4,
      "trend": "stable",
      "artistCount": 55
    },
    {
      "genre": "liquid funk",
      "hours": 590.7,
      "pct": 7.8,
      "trend": "stable",
      "artistCount": 59
    },
    {
      "genre": "classical",
      "hours": 314.3,
      "pct": 4.1,
      "trend": "falling",
      "artistCount": 30
    },
    {
      "genre": "rock",
      "hours": 270.0,
      "pct": 3.5,
      "trend": "stable",
      "artistCount": 7
    },
    {
      "genre": "r&b",
      "hours": 228.9,
      "pct": 3.0,
      "trend": "falling",
      "artistCount": 26
    },
    {
      "genre": "future bass",
      "hours": 223.3,
      "pct": 2.9,
      "trend": "stable",
      "artistCount": 26
    },
    {
      "genre": "classical piano",
      "hours": 207.4,
      "pct": 2.7,
      "trend": "falling",
      "artistCount": 10
    },
    {
      "genre": "nu metal",
      "hours": 183.3,
      "pct": 2.4,
      "trend": "rising",
      "artistCount": 12
    },
    {
      "genre": "melodic bass",
      "hours": 179.4,
      "pct": 2.4,
      "trend": "stable",
      "artistCount": 12
    },
    {
      "genre": "alternative metal",
      "hours": 176.4,
      "pct": 2.3,
      "trend": "stable",
      "artistCount": 11
    },
    {
      "genre": "chillstep",
      "hours": 161.5,
      "pct": 2.1,
      "trend": "rising",
      "artistCount": 19
    },
    {
      "genre": "jungle",
      "hours": 160.9,
      "pct": 2.1,
      "trend": "rising",
      "artistCount": 19
    },
    {
      "genre": "big room",
      "hours": 157.7,
      "pct": 2.1,
      "trend": "falling",
      "artistCount": 25
    },
    {
      "genre": "opera",
      "hours": 157.2,
      "pct": 2.1,
      "trend": "falling",
      "artistCount": 17
    }
  ],
  "byYear": [
    {
      "year": 2016,
      "hours": 28
    },
    {
      "year": 2017,
      "hours": 425
    },
    {
      "year": 2018,
      "hours": 830
    },
    {
      "year": 2019,
      "hours": 840
    },
    {
      "year": 2020,
      "hours": 856
    },
    {
      "year": 2021,
      "hours": 770
    },
    {
      "year": 2022,
      "hours": 612
    },
    {
      "year": 2023,
      "hours": 650
    },
    {
      "year": 2024,
      "hours": 756
    },
    {
      "year": 2025,
      "hours": 721
    },
    {
      "year": 2026,
      "hours": 319
    }
  ],
  "topPodcasts": [
    {
      "show": "The Joe Rogan Experience",
      "hours": 15.4,
      "episodes": 13
    },
    {
      "show": "Shawn Ryan Show",
      "hours": 15.1,
      "episodes": 10
    },
    {
      "show": "This Past Weekend w/ Theo Von",
      "hours": 11.6,
      "episodes": 11
    },
    {
      "show": "Mike Drop",
      "hours": 5.7,
      "episodes": 2
    },
    {
      "show": "Naval",
      "hours": 3.8,
      "episodes": 9
    }
  ]
} as const

export type MusicStats = typeof musicStats
